### PR TITLE
[builtins] std.list.init and std.list.make

### PR DESCRIPTION
**Pull request by FissoreD**

### CODE REVIEW

**Comment by gares** [comment]
Most of the list related APIs are in `std.`, possibly by mistake.
I think `std.list.init` and `std.list.make` are more appropriate names for these two.

**Comment by FissoreD** [comment]
I think the same.
I prefer std.list.null rather then std.null
The same for map, map2, ...

**Comment by FissoreD** [comment]
Should we put the whole think in a namespace like sets and maps ?

**Comment by gares** [comment]
that would break a lot of code, so at least we should keep (deprecated?) aliases. Maybe not in this pr

**Review by gares — APPROVED** [review]

**Pull request merged**
